name: KSEI Monthly Scraper

on:
  schedule:
    - cron: "0 19 6 * *"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run parser
        run: python scraper.py

      - name: Check output
        run: |
          SIZE=$(wc -c < data/ksei.json)
          echo "ksei.json size: $SIZE bytes"
          if [ "$SIZE" -lt 50000 ]; then
            echo "ERROR: File terlalu kecil. Pastikan file .txt ada di data/raw/"
            cat data/ksei.json
            exit 1
          fi
          echo "OK"

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ksei.json
          git diff --staged --quiet || git commit -m "data: update KSEI $(date +'%Y-%m')"
          git push
